# CMake generated Testfile for 
# Source directory: D:/Programowanie/Projekty/test/CoolProp
# Build directory: D:/Programowanie/Projekty/test/CoolProp/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Javatestbuild "javac" "-d" "." "D:/Programowanie/Projekty/test/CoolProp/install_root/Java/Example.java" "-cp" "D:/Programowanie/Projekty/test/CoolProp/install_root/Java/platform-independent")
  set_tests_properties(Javatestbuild PROPERTIES  WORKING_DIRECTORY "D:/Programowanie/Projekty/test/CoolProp/testing_root/Java64")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Javatestbuild "javac" "-d" "." "D:/Programowanie/Projekty/test/CoolProp/install_root/Java/Example.java" "-cp" "D:/Programowanie/Projekty/test/CoolProp/install_root/Java/platform-independent")
  set_tests_properties(Javatestbuild PROPERTIES  WORKING_DIRECTORY "D:/Programowanie/Projekty/test/CoolProp/testing_root/Java64")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Javatestbuild "javac" "-d" "." "D:/Programowanie/Projekty/test/CoolProp/install_root/Java/Example.java" "-cp" "D:/Programowanie/Projekty/test/CoolProp/install_root/Java/platform-independent")
  set_tests_properties(Javatestbuild PROPERTIES  WORKING_DIRECTORY "D:/Programowanie/Projekty/test/CoolProp/testing_root/Java64")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Javatestbuild "javac" "-d" "." "D:/Programowanie/Projekty/test/CoolProp/install_root/Java/Example.java" "-cp" "D:/Programowanie/Projekty/test/CoolProp/install_root/Java/platform-independent")
  set_tests_properties(Javatestbuild PROPERTIES  WORKING_DIRECTORY "D:/Programowanie/Projekty/test/CoolProp/testing_root/Java64")
else()
  add_test(Javatestbuild NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Javatestrun "C:/Program Files/Java/jdk1.8.0_74/bin/java.exe" "-Djava.library.path=D:/Programowanie/Projekty/test/CoolProp/install_root/Java/Windows_64bit" "Example")
  set_tests_properties(Javatestrun PROPERTIES  WORKING_DIRECTORY "D:/Programowanie/Projekty/test/CoolProp/testing_root/Java64")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Javatestrun "C:/Program Files/Java/jdk1.8.0_74/bin/java.exe" "-Djava.library.path=D:/Programowanie/Projekty/test/CoolProp/install_root/Java/Windows_64bit" "Example")
  set_tests_properties(Javatestrun PROPERTIES  WORKING_DIRECTORY "D:/Programowanie/Projekty/test/CoolProp/testing_root/Java64")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Javatestrun "C:/Program Files/Java/jdk1.8.0_74/bin/java.exe" "-Djava.library.path=D:/Programowanie/Projekty/test/CoolProp/install_root/Java/Windows_64bit" "Example")
  set_tests_properties(Javatestrun PROPERTIES  WORKING_DIRECTORY "D:/Programowanie/Projekty/test/CoolProp/testing_root/Java64")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Javatestrun "C:/Program Files/Java/jdk1.8.0_74/bin/java.exe" "-Djava.library.path=D:/Programowanie/Projekty/test/CoolProp/install_root/Java/Windows_64bit" "Example")
  set_tests_properties(Javatestrun PROPERTIES  WORKING_DIRECTORY "D:/Programowanie/Projekty/test/CoolProp/testing_root/Java64")
else()
  add_test(Javatestrun NOT_AVAILABLE)
endif()
